// ISOLE AS CHAVES
export const KEY_ID_DADOS_PESSOAIS = 'dadosPessoais';
export const KEY_CHECK_CNH = 'cnh';
export const KEY_CHECK_PERFIL = 'perfil';

// EM SEGUIDA ADICIONE ELA NA LISTA DE LIMPEZA GERAL
export const KEYS_CLEANNER = {
  KEYS_CADASTRO_ENTREGADOR: [
    KEY_ID_DADOS_PESSOAIS,
    KEY_CHECK_CNH,
    KEY_CHECK_PERFIL,
  ],
};
