// INSOLE AS CHAVES
export const KEY_CADASTRO_DADOS_PESSOAIS = 'KEY_CADASTRO_DADOS_PESSOAIS';
export const KEY_CADASTRO_PHOTOS = 'KEY_CADASTRO_PHOTOS';
export const KEY_CADASTRO_SENHA = 'KEY_CADASTRO_SENHA';
export const KEY_CHECK_CNH = 'cnh';
export const KEY_CHECK_PERFIL = 'perfil';

// EM SEGUIDA ADICIONE ELA NA LISTA DE LIMPEZA GERAL
export const KEYS_CLEANNER = [
  KEY_CADASTRO_DADOS_PESSOAIS,
  KEY_CADASTRO_PHOTOS,
  KEY_CADASTRO_SENHA,
  KEY_CHECK_CNH,
  KEY_CHECK_PERFIL,
];
